language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_install:
  - composer self-update --no-interaction --ansi
  - composer config notify-on-install false
install:
  - composer install --dev --no-progress --no-interaction --ansi --prefer-source
before_script:
  -- echo 'short_open_tag = On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist
